import { AppBar, createTheme, CssBaseline, IconButton, Stack, ThemeProvider, Typography } from "@mui/material"
import theme from "./styles"
import { ArrowBack } from "@mui/icons-material"
import { TasksProvider } from "./context/tasks.provider"
import { Breadcrumbs } from "./components/breadcrumbs"
import { CheckIcon } from "./components/icons"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
        
        <style dangerouslySetInnerHTML={{ __html: `
          a {
            text-decoration: none;
            color: inherit;
          }
        `}} />
      </head>
      <body>
        <ThemeProvider theme={theme}>
          <CssBaseline />

          <AppBar color="default">
            <Breadcrumbs items={[
              {
                node: <IconButton sx={{ margin: "-.5rem 0" }} size="small"><ArrowBack /></IconButton>,
              },
              {
                node: <Stack direction="row" spacing={1} alignItems="center"><CheckIcon sx={{ w: "1.25rem", h: "1.25rem" }} /><Typography>Задачи</Typography></Stack>
              }
            ]} />
          </AppBar>

          <TasksProvider>
            {children}
          </TasksProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
